language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "lucasantopadre"
    token:
      secure: da7ba880306b9aea3a14aecca38a864f1799ee45
script:
  - ant build
  - sonar-scanner