language: java
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "lucasantopadre"
    token:
      secure: b00c74e26ac3551af45e5bce8caf986beae04811
script:
  - ant build
  - sonar-scanner